/** Generated by prebuild.js — do not edit by hand */
export const entries = [
  { title: "Astro Mix Blog", date: "2026-04-05", url: "/post/Astro-Mix-Blog.html", pinned: true },
  { title: "哲学的天真与危险", date: "2026-04-03", url: "/post/哲学的天真与危险.jpg" },
  { title: "奥古斯丁 阿奎那 路德 加尔文", date: "2026-04-03", url: "/post/奥古斯丁 阿奎那 路德 加尔文.png" },
  { title: "Askin博客月刊 第三期 26.03", date: "2026-03-30", url: "/post/Askin博客月刊 第三期 26.03.html" },
  { title: "Askin博客月刊 第二期 26.02", date: "2026-02-28", url: "/post/Askin博客月刊 第二期 26.02.html" },
  { title: "Askin博客月刊 第一期 26.01", date: "2026-01-30", url: "/post/Askin博客月刊 第一期 26.01.html" },
];
